# Generated by Django 2.0.6 on 2018-06-12 17:59

from django.db import migrations, models
import fifawc.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Display/Profile Picture of the User', null=True, upload_to=fifawc.users.models.get_dp_path),
        ),
    ]
