# Generated by Django 2.0.6 on 2018-06-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_points_scored'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points_scored',
        ),
    ]
