# Generated by Django 2.0.6 on 2018-06-12 17:59

from django.db import migrations, models
import django.db.models.deletion
import match.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'Group A'), (2, 'Group B'), (3, 'Group C'), (4, 'Group D'), (5, 'Group E'), (6, 'Group F'), (7, 'Group G'), (8, 'Group H')], default=1)),
                ('flag_image', models.ImageField(upload_to=match.models.get_flag_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('match_type', models.PositiveSmallIntegerField(choices=[(1, 'Group Stage'), (2, 'Round of 16'), (3, 'Quarter-finals'), (4, 'Semi-finals'), (5, 'Third Place Play-Off'), (6, 'Final')], default=1)),
                ('away', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='match.Country')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='match.Country')),
            ],
        ),
    ]
